#!/usr/bin/env bash
# PLUGIN_NAME: CLAUDE.md Auto-Generator
# PLUGIN_PHASE: pre
#
# claudemd_gen.sh — Generates or updates CLAUDE.md in target repos
#
# Phase: pre (runs before shift starts)
# Purpose: Create a CLAUDE.md file that gives Claude Code optimal context
#          about the project structure, conventions, and commands.
#
# Usage:
#   Enable by copying to plugins/pre/claudemd_gen.sh
#
# Configuration:
#   CLAUDEMD_OVERWRITE=false  # Set true to regenerate each shift
#   CLAUDEMD_TARGET=.         # Target project directory

set -euo pipefail

NIGHT_SHIFT_DIR="${NIGHT_SHIFT_DIR:-$(cd "$(dirname "$(realpath "$0")")/../.." && pwd)}"
CLAUDEMD_OVERWRITE="${CLAUDEMD_OVERWRITE:-false}"
CLAUDEMD_TARGET="${CLAUDEMD_TARGET:-.}"

log() { echo "[claudemd_gen] $(date '+%H:%M:%S') $1"; }

generate_claudemd() {
    local project_dir="$CLAUDEMD_TARGET"
    local claude_md="$project_dir/CLAUDE.md"

    # Skip if file exists and overwrite is disabled
    if [ -f "$claude_md" ] && [ "$CLAUDEMD_OVERWRITE" != "true" ]; then
        log "SKIP: CLAUDE.md already exists (set CLAUDEMD_OVERWRITE=true to regenerate)"
        return 0
    fi

    cd "$project_dir" || return 1

    log "Generating CLAUDE.md for $(basename "$(pwd)")..."

    # ── Detect project info ──
    local project_name
    project_name=$(basename "$(pwd)")

    local language="unknown"
    local package_manager=""
    local test_cmd=""
    local build_cmd=""
    local lint_cmd=""
    local dev_cmd=""

    # Node.js / TypeScript
    if [ -f "package.json" ]; then
        if [ -f "tsconfig.json" ]; then
            language="TypeScript"
        else
            language="JavaScript"
        fi

        # Detect package manager
        if [ -f "pnpm-lock.yaml" ]; then
            package_manager="pnpm"
        elif [ -f "yarn.lock" ]; then
            package_manager="yarn"
        elif [ -f "bun.lockb" ]; then
            package_manager="bun"
        else
            package_manager="npm"
        fi

        # Extract scripts
        if command -v node &>/dev/null; then
            test_cmd=$(node -e "try{const p=require('./package.json');if(p.scripts?.test)console.log('$package_manager test')}catch(e){}" 2>/dev/null)
            build_cmd=$(node -e "try{const p=require('./package.json');if(p.scripts?.build)console.log('$package_manager run build')}catch(e){}" 2>/dev/null)
            lint_cmd=$(node -e "try{const p=require('./package.json');if(p.scripts?.lint)console.log('$package_manager run lint')}catch(e){}" 2>/dev/null)
            dev_cmd=$(node -e "try{const p=require('./package.json');if(p.scripts?.dev)console.log('$package_manager run dev')}catch(e){}" 2>/dev/null)
        fi

    elif [ -f "Cargo.toml" ]; then
        language="Rust"
        test_cmd="cargo test"
        build_cmd="cargo build"
        lint_cmd="cargo clippy"

    elif [ -f "go.mod" ]; then
        language="Go"
        test_cmd="go test ./..."
        build_cmd="go build ./..."
        lint_cmd="golangci-lint run"

    elif [ -f "pyproject.toml" ] || [ -f "setup.py" ]; then
        language="Python"
        test_cmd="pytest"
        lint_cmd="ruff check ."
        if [ -f "pyproject.toml" ] && grep -q "poetry" "pyproject.toml" 2>/dev/null; then
            package_manager="poetry"
        elif [ -f "pyproject.toml" ] && grep -q "uv" "pyproject.toml" 2>/dev/null; then
            package_manager="uv"
        else
            package_manager="pip"
        fi
    fi

    # ── Detect git info ──
    local base_branch="main"
    if git show-ref --verify --quiet refs/heads/main 2>/dev/null; then
        base_branch="main"
    elif git show-ref --verify --quiet refs/heads/master 2>/dev/null; then
        base_branch="master"
    fi

    # ── Detect directory structure ──
    local dir_structure
    dir_structure=$(find . -maxdepth 2 -type d \
        ! -path './node_modules*' \
        ! -path './.git*' \
        ! -path './target*' \
        ! -path './__pycache__*' \
        ! -path './dist*' \
        ! -path './build*' \
        ! -path './.next*' \
        ! -path './vendor*' \
        2>/dev/null | sort | head -30 | sed 's/^/  /')

    # ── Detect CI ──
    local ci_info=""
    if [ -d ".github/workflows" ]; then
        ci_info="GitHub Actions"
    elif [ -f ".gitlab-ci.yml" ]; then
        ci_info="GitLab CI"
    elif [ -f "Jenkinsfile" ]; then
        ci_info="Jenkins"
    elif [ -f ".circleci/config.yml" ]; then
        ci_info="CircleCI"
    fi

    # ── Generate CLAUDE.md ──
    cat > "$claude_md" << CLAUDEMD
# CLAUDE.md

> This file provides context for AI coding assistants working on this project.
> Auto-generated by [AI Night Shift](https://github.com/JudyaiLab/ai-night-shift).

## Project: $project_name

- **Language:** $language
${package_manager:+- **Package manager:** $package_manager}
${ci_info:+- **CI:** $ci_info}
- **Base branch:** $base_branch

## Commands

${test_cmd:+- **Test:** \`$test_cmd\`}
${build_cmd:+- **Build:** \`$build_cmd\`}
${lint_cmd:+- **Lint:** \`$lint_cmd\`}
${dev_cmd:+- **Dev server:** \`$dev_cmd\`}

## Project Structure

\`\`\`
$dir_structure
\`\`\`

## Conventions

- Commit messages: use conventional commits (feat:, fix:, chore:, etc.)
- Branch naming: feature/<name>, fix/<name>, chore/<name>
- Always run tests before committing
- Do not modify .env files or commit secrets

## Important Files

$([ -f "package.json" ] && echo "- \`package.json\` — project dependencies and scripts")
$([ -f "tsconfig.json" ] && echo "- \`tsconfig.json\` — TypeScript configuration")
$([ -f "Cargo.toml" ] && echo "- \`Cargo.toml\` — Rust project configuration")
$([ -f "go.mod" ] && echo "- \`go.mod\` — Go module definition")
$([ -f "pyproject.toml" ] && echo "- \`pyproject.toml\` — Python project configuration")
$([ -f "Dockerfile" ] && echo "- \`Dockerfile\` — Container definition")
$([ -f "docker-compose.yml" ] && echo "- \`docker-compose.yml\` — Service orchestration")
CLAUDEMD

    log "Generated CLAUDE.md ($language project)"
}

# === Main ===
generate_claudemd
