#!/usr/bin/env bash
# PLUGIN_NAME: Morning Report Generator
# PLUGIN_PHASE: post
# PLUGIN_DESCRIPTION: Compiles all night shift data into a morning briefing

set -euo pipefail

NIGHT_SHIFT_DIR="${NIGHT_SHIFT_DIR:-$(cd "$(dirname "$0")/../.." && pwd)}"
REPORTS_DIR="${NIGHT_SHIFT_DIR}/reports"
LOGS_DIR="${NIGHT_SHIFT_DIR}/logs"
NIGHT_CHAT="${NIGHT_SHIFT_DIR}/protocols/night_chat.md"
DATE_TAG=$(date +%Y-%m-%d)

MORNING_REPORT="${REPORTS_DIR}/${DATE_TAG}_morning_briefing.md"

echo "=== Morning Report Generator ==="

{
    echo "# Morning Briefing — $DATE_TAG"
    echo ""
    echo "> Automatically generated at $(date '+%H:%M %Z')"
    echo ""

    # Night shift summary
    SUMMARY="${REPORTS_DIR}/${DATE_TAG}_summary.md"
    if [ -f "$SUMMARY" ]; then
        echo "## Night Shift Summary"
        cat "$SUMMARY"
        echo ""
    fi

    # Health report
    HEALTH="${REPORTS_DIR}/${DATE_TAG}_health.md"
    if [ -f "$HEALTH" ]; then
        echo "## System Health"
        # Just the summary section
        sed -n '/^## Summary/,$ p' "$HEALTH"
        echo ""
    fi

    # Git activity
    GIT_SUMMARY="${REPORTS_DIR}/${DATE_TAG}_git_summary.md"
    if [ -f "$GIT_SUMMARY" ]; then
        echo "## Code Changes"
        cat "$GIT_SUMMARY"
        echo ""
    fi

    # Night chat highlights (last 20 messages)
    if [ -f "$NIGHT_CHAT" ]; then
        echo "## Agent Communication (Latest)"
        echo '```'
        tail -20 "$NIGHT_CHAT"
        echo '```'
        echo ""
    fi

    echo "---"
    echo "*Generated by AI Night Shift — Morning Report Plugin*"

} > "$MORNING_REPORT"

echo "Morning briefing: $MORNING_REPORT"

# ── Optional: Send to Telegram ──
if [ -n "${TELEGRAM_BOT_TOKEN:-}" ] && [ -n "${TELEGRAM_CHAT_ID:-}" ]; then
    # Create a concise TG-friendly version
    TG_MSG=$(head -30 "$MORNING_REPORT" | sed 's/#//g' | head -20)

    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        -d chat_id="$TELEGRAM_CHAT_ID" \
        -d text="$TG_MSG" \
        -d parse_mode="Markdown" \
        > /dev/null 2>&1 || echo "WARN: Failed to send TG notification"

    echo "TG notification sent"
fi
